language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.20"
  - "5.18"
install:
  - cpanm --quiet --notest --force --skip-satisfied --installdeps .
  - cpanm --quiet --notest --skip-satisfied Devel::Cover
script:
  - perl Build.PL && cover -test
after_success:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -report coveralls
env: NETWORK_TEST=1
